name: ðŸš€CI run (MERGING) QA on CheckPassâœ…
run-name: ${{github.actor}}ðŸ‘¾ merged into MAIN from ${{github.ref_name}}

on:
  pull_request:
    types:
      - opened
    branches:
      - QA

jobs:
    AutoMerge-into-Main:
        runs-on: ubuntu-latest
        steps:
          - name: ðŸ§¬Merge QA -> MAIN
            uses: devmasx/merge-branch@master
            with:
             type: now
             label_name: 'automatedPullRequest'
             target_branch: 'cypex' #ESTE ES LA RAMA PRINCIPAL DEL REPOSITORIO PRESENTE
             github_token: ${{ github.token }}
            