#*ü§ñEste Pipeline de CI se activa al PUSHEAR o MERGEAR en ramas de tareas que no sean QA ni Main, y consiste en ejecutar los tests de una US e importar los resultados a Jira!üöÄ
#*üë©üèª‚Äçüî¨Para utilizar este Pipeline de Ari, sigue los siguientes pasos:
#todo: 1 -> Crea tu propio archivo sanity.yml con tu username de GitHub, ejemplo sanity-saiotest.yml
#todo: 2 -> Copia el contenido de este archivo yml y p√©galo en tu nuevo archivo yml con tu username.
#todo: 3 -> Modifica el trigger del Push en donde dice "TuBranchAqui", coloca tu nombre tal cual de tu rama git.
#todo: 4 -> Modifica el archivo de prueba a ejectuar en el script del "yarn test" (ver ejemplo en este archivo)
#todo: 5 -> Modifica la propiedad: "testExecKey" con tu ID del TX de Jira para importar autom√°ticamente el resultado.
#todo: 6 -> Recuerda modificar el projectKey correspondiente, si est√°s en L3, debe ser GX3 y as√≠...
#todo: 7 -> Listo! Guarda los cambios (git add + git commit) y pushea (git push) para ejectutar este Pipeline!
#*Resultado: Deber√≠a ejecutarse este Pipeline de GitHub Actions y correr cada uno de los Jobs declarados aqu√≠.

name: üß™Pipeline SanityTest
run-name: ${{github.actor}}üë®üèª‚Äçüî¨ triggered SanityTest in ${{github.ref_name}}

on:
  push:
    branches: ['TuBranchAqui'] #! Cambia "TuBranchAqui" por el nombre de tu rama de tarea.
  workflow_dispatch:


jobs:
  SanityTest:
    runs-on: ubuntu-latest

    steps:
    - name: üíªCheckout
      uses: actions/checkout@v4

    - name: üíøInstall Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: üçô Bun Setup
      uses: oven-sh/setup-bun@v1

    - name: üß¨Install All Dependencies
      run: |
        bun install

    - name: üß™Cypress Run Test Coverage
      uses: cypress-io/github-action@v4
      with:
        browser: chrome
        command: | #todo: EDITAR AQU√ç EL ARCHIVO SUITE A EJECUTAR:
          bun run test:chrome cypress/e2e/Tests/Checkout/GX3-1870_spaceCheckout.cy.ts

    - name: üì¨Generate JUnit/Mocha Report
      if: always()
      run: |
        bun run chrome:report

    - name: ‚úÖCheck if XRAY_CLIENT is Defined
      if: always()
      run: |
        if [[ -z "${{ secrets.XRAY_CLIENT_ID }}" ]]; then
          echo "XRAY_CLIENT_ID is not set. Please set it in the repository secrets to enable Slack notifications."
        fi
        if [[ -z "${{ secrets.XRAY_CLIENT_SECRET }}" ]]; then
          echo "XRAY_CLIENT_SECRET is not set. Please set it in the repository secrets to enable Slack notifications."
        fi

    - name: ‚úÖImport Test Results to Xray
      if: env.XRAY_CLIENT != '' && env.XRAY_SECRET != ''
      uses: mikepenz/xray-action@v3
      with: #OPCIONES PARA IMPORTAR LOS RESULTADOS DE PRUEBA A JIRA XRAY:
        username: ${{secrets.XRAY_CLIENT_ID}}
        password: ${{secrets.XRAY_CLIENT_SECRET}}
        testFormat: 'junit' #! NO CAMBIAR
        testPaths: 'cypress/tests_results/junit/chrome_regression_report.xml' #! NO CAMBIAR
        testExecKey: 'GX3-1328' #todo: EDITAR AQU√ç EL TEST EXECUTION A IMPORTAR LAS PRUEBAS.
        projectKey: 'GX3' #todo: EDITAR EN CASO DE TRABAJAR CON OTRO PROYECTO.
      env:
        XRAY_CLIENT: ${{ secrets.XRAY_CLIENT_SECRET }}
        XRAY_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}

    - name: üìäUpload Artifact Mochawesome Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: sanity-mocha-report
        path: cypress/tests_reports/chrome_mocha_report
        retention-days: 15

    - name: üîîCheck if SLACK_WEBHOOK is Defined
      if: always()
      run: |
        if [[ -z "${{ secrets.SLACK_WEBHOOK }}" ]]; then
          echo "SLACK_WEBHOOK is not set. Please set it in the repository secrets to enable Slack notifications."
        fi

    - name: üîîSlack Notification of Done
      if: env.SLACK_WEBHOOK != ''
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Ari‚ú®
        SLACK_MESSAGE: ':test_tube: CYPRESS: SanityTest is Done and imported to Jira :rocket:'
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://image.cdn2.seaart.ai/2023-12-06/clo9g0h4msbc73ac2sog/99e1abc36f32945cd4bacf5ee7448e96194545f7_high.webp
