name: ðŸ”€CI Run US-GX-007 | Test Simple CI Run File
run-name: ðŸ§ªIn-Sprint Testing Execution by ${{github.actor}}

on: [push]

jobs:
  QA-Cypress-TestSuite-Execution:
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v3

      - name: Cypress.ioâœ…
        uses: cypress-io/github-action@v4.2.0
        with: 
          browser: chrome
          spec: "*/**/sintaxis.cy.js"

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

